src/Richpolis/BackendBundle/Entity/Configuraciones.php
<?php

namespace Richpolis\BackendBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Configuraciones
 *
 * @ORM\Table(name="configuraciones")
 * @ORM\Entity(repositoryClass="Richpolis\BackendBundle\Repository\ConfiguracionesRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Configuraciones
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="configuracion", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $configuracion;

    /**
     * @var integer
     *
     * @ORM\Column(name="tipo_archivo", type="integer", length=1)
     * @Assert\NotBlank()
     */
    private $tipoConfiguracion;

    /**
     * @var string
     *
     * @ORM\Column(name="texto", type="text",nullable=true)
     */
    private $texto;
    
    /**
     * @var boolean
     *
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;    

    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=255,nullable=true)
     */
    private $slug;

    static public $IMAGEN=1;
    static public $LINK_VIDEO=2;
    static public $TEXTO_LARGO=3;
    static public $TEXTO_CORTO=4;
    
    
    
    static private $sCategorias=array(
        1=>'Imagen',
        2=>'Link_video',
        3=>'Texto largo',
        4=>'Texto corto',
    );
    
    public function getStringTipoConfiguracion(){
        return self::$sCategorias[$this->getTipoConfiguracion()];
    }

    static function getArrayTipoConfiguracion(){
        return self::$sCategorias;
    }

    static function getPreferedTipoConfiguracion(){
        return array(self::$TEXTO_CORTO);
    }
    
    public function __construct() {
        $this->isActive = true;
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set configuracion
     *
     * @param string $configuracion
     * @return Configuraciones
     */
    public function setConfiguracion($configuracion)
    {
        $this->configuracion = $configuracion;
        
        return $this;
    }

    /**
     * Get configuracion
     *
     * @return string 
     */
    public function getConfiguracion()
    {
        return $this->configuracion;
    }

    /**
     * Set tipo
     *
     * @param integer $tipo
     * @return Configuraciones
     */
    public function setTipoConfiguracion($tipo)
    {
        $this->tipoConfiguracion = $tipo;
    
        return $this;
    }

    /**
     * Get tipo
     *
     * @return integer 
     */
    public function getTipoConfiguracion()
    {
        return $this->tipoConfiguracion;
    }
    
    /**
     * Set texto
     *
     * @param string $texto
     * @return Configuraciones
     */
    public function setTexto($texto)
    {
        $this->texto = $texto;
    
        return $this;
    }

    /**
     * Get texto
     *
     * @return string 
     */
    public function getTexto()
    {
        return $this->texto;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Configuraciones
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    
        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }
    
    /*
     * Slugable
     */
    
    /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function setSlugAtValue()
    {
        $this->slug = \Richpolis\BackendBundle\Utils\Richsys::slugify($this->getConfiguracion());
    }
    
    
    /**
    ** @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function preSaveLinkVideo()
    {
      if ($this->getTipoConfiguracion()==self::$LINK_VIDEO) {
        $infoVideo=  \Richpolis\BackendBundle\Utils\Richsys::getTitleAndImageVideoYoutube($this->getTexto());
        $this->setTexto($infoVideo['urlVideo']);
      }
    }
    
    /*
     * uploads file
     */
    
    public $file;
    
    /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function preUpload()
    {
      if (null !== $this->file) {
        // do whatever you want to generate a unique name
        $this->texto = uniqid().'.'.$this->file->guessExtension();
      }
    }

    /**
    * @ORM\PostPersist
    * @ORM\PostUpdate
    */
    public function upload()
    {
      if (null === $this->file) {
        return;
      }

      // if there is an error when moving the file, an exception will
      // be automatically thrown by move(). This will properly prevent
      // the entity from being persisted to the database on error
      $this->file->move($this->getUploadRootDir(), $this->texto);

      
      unset($this->file);
    }

    /**
    * @ORM\PostRemove
    */
    public function removeUpload()
    {
      if($this->getTipoConfiguracion()==self::$IMAGEN){  
        if ($file = $this->getAbsolutePath()) {
          if(file_exists($file)){
              unlink($file);
          }
        }
      }
    }
    
    protected function getUploadDir()
    {
        return '/uploads/configuraciones';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../html'.$this->getUploadDir();
    }
    
    protected function getThumbnailRootDir()
    {
        return __DIR__.'/../../../../html'.$this->getUploadDir().'/thumbnails';
    }
        
    public function getWebPath()
    {
        return null === $this->texto ? null : $this->getUploadDir().'/'.$this->texto;
    }
    
    public function getAbsolutePath()
    {
        return null === $this->texto ? null : $this->getUploadRootDir().'/'.$this->texto;
    }
    
    public function isImagen(){
        return $this->getTipoConfiguracion() == Configuraciones::$IMAGEN;
    }
    
    public function isLinkVideo(){
        return $this->getTipoConfiguracion() == Configuraciones::$LINK_VIDEO;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return Configuraciones
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;
    
        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }
}

src/Richpolis/BackendBundle/Resources/views/layout.html.twig
{% extends '::base.html.twig' %}

{% block title %}Administrador{% endblock %}

{% block viewport %} 
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
{% endblock %}

{% block stylesheets %}
<!-- Stylesheets -->
<link rel="stylesheet" href="{{asset('css/bootstrap.css')}}">
<link rel="stylesheet" href="{{asset('css/font-awesome.css')}}">
<link rel="stylesheet" href="{{asset('css/style.css')}}">
<link rel="stylesheet" href="{{asset('css/bootstrap-responsive.html')}}">
<link rel="stylesheet" href="{{asset('css/admin.css')}}">
{% endblock %}

{% block body %}

  {% set route = app.request.get('_route') %}

  {% set usuarios = "" %}
  {% set categorias = "" %}
  {% set publicaciones = "" %}
  {% set publicidad = "" %}
  {% set galerias = "" %}
  {% set configuraciones = "" %}

  {% if route == "categorias_publicaciones" %}
    {% set categorias = "class=open" %}
  {% elseif route == "backend_usuarios" %}
    {% set usuarios = "class=open" %}
  {% elseif route == "publicaciones" %}
    {% set publicaciones = "class=open" %}
  {% elseif route == "publicidad" %}
    {% set publicidad = "class=open" %}
  {% elseif route == "galerias" %}
    {% set galerias = "class=open" %}     
  {% elseif route == "configuraciones" %}
    {% set configuraciones = "class=open" %}       
  {% endif %}
      
<header>
    <div class="navbar navbar-fixed-top bs-docs-nav" role="banner">
        <div class="container">
            <!-- Menu button for smallar screens -->
            <div class="navbar-header">
                <button class="navbar-toggle btn-navbar" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                    <span>Menu</span>
                </button>
                <a href="#" class="pull-left menubutton hidden-xs">
                    <i class="fa fa-bars"></i>
                </a>
                <!-- Site name for smallar screens -->
                <a href="{{path('backend_homepage')}}" class="navbar-brand">
                    <span class="bold">Dashboard</span>
                </a>
            </div>

            <!-- Navigation starts -->
            <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">         

                <!-- Links -->
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown pull-right user-data">            
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                {% if app.user.imagen | length > 0 %}
                                <img src="{{app.user.webPath}}" width="25" height="25" style="border-radius: 50%;"/>    
                                {% else %}
                                <img src="/apple-touch-icon.png" width="25" height="25"/>
                                {% endif %}
                                {{app.user.username|default('anonimo')}} <b class="caret"></b>
                                
                            </a>

                            <!-- Dropdown menu -->
                            <ul class="dropdown-menu">
                                <li><a href="{{path('users_show',{'id':app.user.id})}}"><i class="fa fa-user"></i> Perfil</a></li>
                                <!--li><a href="#"><i class="fa fa-cogs"></i> Settings</a></li-->
                                <li>
                                    <a href="{{path('backend_logout')}}">
                                        <i class="fa fa-key"></i> Salir
                                    </a>
                                </li>
                            </ul>
                    </li>
                </ul>
            </nav>

        </div>
    </div>
</header>
<!-- Main content starts -->
<div class="content">
    <!-- Sidebar -->
    <div class="sidebar">
        <div class="sidebar-dropdown">
            <a href="#">Navegador</a>
        </div>
        <!-- Search form -->
        <form class="navbar-form" role="search" action="#search" method="post">
            <div class="form-group">
                <input id="buscarItem" name="buscarItem" type="text" class="form-control" placeholder="buscar">
                <button class="btn search-button" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </form>
        <!--- Sidebar navigation -->
        <!-- If the main navigation has sub navigation, then add the class "has_sub" to "li" of main navigation. -->
        <ul id="nav">
            <!-- Main menu with font awesome icon -->
            <li>
                <a href="{{path('paginas')}}">
                    <i class="fa fa-sitemap"></i> <span>Paginas</span>
                </a>
            </li>
            <li class="has_sub">
                <a href="#">
                    <i class="fa fa-comment"></i> <span>Categorias</span> <span class="pull-right"><i class="fa fa-chevron-left"></i></span>
                </a>
                {% render(controller('PublicacionesBundle:CategoriaPublicacion:ulTipos')) %}
            </li>
            <li class="has_sub">
                <a  href="#">
                    <i class="fa fa-copy"></i> <span>Publicaciones</span> <span class="pull-right"><i class="fa fa-chevron-left"></i></span>
                </a>
                {% render(controller('PublicacionesBundle:CategoriaPublicacion:ulPublicaciones')) %}
            </li>
            <li>
                <a href="{{path('comentarios')}}">
                    <i class="fa fa-sitemap"></i> <span>Comentarios</span>
                </a>
            </li>
            <li class="has_sub">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Publicidad</span> <span class="pull-right"><i class="fa fa-chevron-left"></i></span>
                </a>
                {% render(controller('PublicidadBundle:Publicidad:ul')) %}
            </li>
            
            {% if is_granted('ROLE_ADMIN') %}
            <li>
                <a {{usuarios}} href="{{path('users')}}">
                    <i class="fa fa-user"></i> <span>Usuarios</span>
                </a>
            </li>
            <li>
                <a {{configuraciones}} href="{{path('configuraciones')}}">
                    <i class="fa fa-gears"></i> <span>Configuraciones</span>
                </a>
            </li>
            {% endif %}    
        </ul>
    </div>
<!-- Sidebar ends -->
	{% block mainbar %} {% endblock %}
</div>
<!-- Content ends -->
<!-- Footer starts -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
               <!-- Copyright info -->
                <!--p class="copy">Copyright &copy; 2012 | <a href="#">Your Site</a> </p-->
                <p></p>
            </div>
        </div>
    </div>
</footer> 	
<!-- Footer ends -->
<!-- Scroll to top -->
<span class="totop"><a href="#"><i class="fa fa-chevron-up"></i></a></span>
<div class="loader"></div>
{% endblock %}

{% block javascripts %}
    <!-- JS -->
    <script src="{{asset('js/jquery.js')}}"></script>
    <script src="{{asset('js/underscore-min.js')}}"></script>
    <script src="{{asset('js/backbone-min.js')}}"></script>
    <script src="{{asset('js/swig.js')}}"></script>
    <script src="{{asset('js/bootstrap.js')}}"></script>
    

{% endblock %}