src/Richpolis/PublicidadBundle/Entity/Publicidad.php
<?php

namespace Richpolis\PublicidadBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Richpolis\BackendBundle\Utils\Richsys as RpsStms;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;


/**
 * Publicidad
 *
 * @ORM\Table(name="publicidad")
 * @ORM\Entity(repositoryClass="Richpolis\PublicidadBundle\Repository\PublicidadRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Publicidad
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="empresa", type="string", length=255, nullable=true)
     */
    private $empresa;
    
    /**
     * @var string
     *
     * @ORM\Column(name="link", type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @var string
     *
     * @ORM\Column(name="archivo", type="string", length=255, nullable=false)
     */
    private $archivo;
    
    /**
     * @var string
     *
     * @ORM\Column(name="tipo_archivo", type="integer")
     */
    private $tipoArchivo;
    
    /**
     * @var string
     *
     * @ORM\Column(name="tipo_publicidad", type="integer")
     */
    private $tipoPublicidad;

    /**
     * @var integer
     *
     * @ORM\Column(name="position", type="integer")
     */
    private $position;

    /**
     * @var boolean
     *
     * @ORM\Column(name="isActive", type="boolean")
     */
    private $isActive;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updatedAt", type="datetime")
     */
    private $updatedAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="vigencia", type="date", nullable=true)
     */
    private $vigencia;
    
    const TIPO_PUBLICIDAD_ENCABEZADO_IZQUIERDO=1;
    const TIPO_PUBLICIDAD_ENCABEZADO_DERECHO=2;
    const TIPO_PUBLICIDAD_ASIDE_ARRIBA=3;
    const TIPO_PUBLICIDAD_ASIDE_ABAJO=4;
        
    static public $sTipoPublicidad=array(
        self::TIPO_PUBLICIDAD_ENCABEZADO_IZQUIERDO=>'Supper Banner 728 X 100',
        self::TIPO_PUBLICIDAD_ENCABEZADO_DERECHO=>'Micro Banner 230 X 100',
        self::TIPO_PUBLICIDAD_ASIDE_ARRIBA=>'Box Banner 1 300 X 250',
        self::TIPO_PUBLICIDAD_ASIDE_ABAJO=>'Box Banner 2 300 X 250',
    );
    
	
    public function __construct() {
        $this->isActive = true;
        $this->vigencia = new \DateTime("+1 month");
        $this->tipoArchivo = RpsStms::TIPO_ARCHIVO_IMAGEN;  
	$this->tipoPublicidad = Publicidad::TIPO_PUBLICIDAD_ENCABEZADO_DERECHO;
    }
    
    public function getStringTipoArchivo(){
        return RpsStms::$sTipoArchivo[$this->getTipoArchivo()];
    }

    static function getArrayTipoArchivos(){
        return RpsStms::$sTipoArchivo;
    }

    static function getPreferedTipoArchivo(){
        return array(RpsStms::$TIPO_ARCHIVO_IMAGEN);
    }

    public function getStringTipoPublicidad(){
        return self::$sTipoPublicidad[$this->getTipoPublicidad()];
    }

    static function getArrayTipoPublicidad(){
        return self::$sTipoPublicidad;
    }

    static function getPreferedTipoPublicidad(){
        return array(self::TIPO_PUBLICIDAD_ENCABEZADO_IZQUIERDO);
    }
    
    
    public function isVigenciaCorrecta(){
        
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set archivo
     *
     * @param string $archivo
     * @return Publicidad
     */
    public function setArchivo($archivo)
    {
        $this->archivo = $archivo;

        return $this;
    }

    /**
     * Get archivo
     *
     * @return string 
     */
    public function getArchivo()
    {
        return $this->archivo;
    }

    /**
     * Set position
     *
     * @param integer $position
     * @return Publicidad
     */
    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return integer 
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return Publicidad
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Publicidad
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Publicidad
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set vigencia
     *
     * @param \DateTime $vigencia
     * @return Publicidad
     */
    public function setVigencia($vigencia)
    {
        $this->vigencia = $vigencia;

        return $this;
    }

    /**
     * Get vigencia
     *
     * @return \DateTime 
     */
    public function getVigencia()
    {
        return $this->vigencia;
    }

    /**
     * Set empresa
     *
     * @param string $empresa
     * @return Publicidad
     */
    public function setEmpresa($empresa)
    {
        $this->empresa = $empresa;

        return $this;
    }

    /**
     * Get empresa
     *
     * @return string 
     */
    public function getEmpresa()
    {
        return $this->empresa;
    }

    /**
     * Set link
     *
     * @param string $link
     * @return Publicidad
     */
    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    /**
     * Get link
     *
     * @return string 
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Set tipoArchivo
     *
     * @param integer $tipoArchivo
     * @return Publicidad
     */
    public function setTipoArchivo($tipoArchivo)
    {
        $this->tipoArchivo = $tipoArchivo;

        return $this;
    }

    /**
     * Get tipoArchivo
     *
     * @return integer 
     */
    public function getTipoArchivo()
    {
        return $this->tipoArchivo;
    }

    /**
     * Set tipoPublicidad
     *
     * @param integer $tipoPublicidad
     * @return Publicidad
     */
    public function setTipoPublicidad($tipoPublicidad)
    {
        $this->tipoPublicidad = $tipoPublicidad;

        return $this;
    }

    /**
     * Get tipoPublicidad
     *
     * @return integer 
     */
    public function getTipoPublicidad()
    {
        return $this->tipoPublicidad;
    }
    
    
    /*
     * Timestable
     */
    
    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        if(!$this->getCreatedAt()){
          $this->createdAt = new \DateTime();
        }
        if(!$this->getUpdatedAt()){
          $this->updatedAt = new \DateTime();
        }
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTime();
    }
	
    
    /*** uploads ***/
    
    public $file;
    
    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->archivo)) {
            // store the old name to delete after the update
            $this->temp = $this->archivo;
            $this->archivo = null;
        } else {
            $this->archivo = 'initial';
        }
    }
    
    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }
    
    /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function preUpload()
    {
      if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->archivo = $filename.'.'.$this->getFile()->guessExtension();
            $this->setTipoArchivo(RpsStms::getTipoArchivo($this->getArchivo()));
        }
    }

    /**
    * @ORM\PostPersist
    * @ORM\PostUpdate
    */
    public function upload()
    {
      if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->archivo);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;

src/Richpolis/PublicidadBundle/Form/PublicidadType.php
<?php

namespace Richpolis\PublicidadBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PublicidadType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('empresa','text',array(
                'label'=>'Empresa','required'=>true,'attr'=>array(
                    'class'=>'form-control placeholder',
                    'placeholder'=>'Empresa',
                    'data-bind'=>'value: empresa'
                    )
                ))
            ->add('file','file',array('label'=>'Archivo','attr'=>array(
                'class'=>'form-control placeholder',
                'placeholder'=>'Archivo',
                'data-bind'=>'value: archivo'
             )))
            ->add('link','url',array(
                'label'=>'Link','required'=>false,'attr'=>array(
                    'class'=>'form-control placeholder',
                    'placeholder'=>'Link de pagina (solo imagenes)',
                    'data-bind'=>'value: link'
                    )
                ))    
            ->add('isActive',null,array('label'=>'Activo?','attr'=>array(
                'class'=>'checkbox-inline',
                'placeholder'=>'Es activo',
                'data-bind'=>'value: isActive'
                )))
            ->add('archivo','hidden')
            ->add('position','hidden')
            ->add('tipoPublicidad','hidden')
            ->add('tipoArchivo','hidden')    
            ->add('vigencia')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Richpolis\PublicidadBundle\Entity\Publicidad'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'richpolis_publicidadbundle_publicidad';
    }
}

src/Richpolis/PublicidadBundle/Resources/views/Publicidad/item.html.twig
<tr id="registro-{{entity.id}}" data-id="{{entity.id}}">
    <td><a href="{{ path('publicidad_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
    <td>{{ entity.empresa }}</td>
    <td>
        {% if entity.archivo | length > 0 %}
            {{ entity.archivoMiniView | raw }}
        {% else  %}
            sin imagen 
        {% endif %}
    </td>
    <td>{% if entity.vigencia %}{{ entity.vigencia|date('d-m-Y') }}{% endif %}</td>
    <td class="is-active" data-url="{{ path('publicidad_is_active',{'id': entity.id }) }}">
        {% if entity.isActive %}
            <button class="btn btn-success activo"><i class="fa fa-check-square-o"></i></button>
        {% else %}
            <button class="btn btn-info inactivo"><i class="fa fa-square-o"></i></button>
        {% endif %}
    </td>
    <td>
        <button onclick="javascript:editarRegistro('{{ path('publicidad_edit', { 'id': entity.id }) }}')" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> </button>
        <button onclick="javascript:editarRegistro('{{ path('publicidad_show', { 'id': entity.id }) }}', '#registro-{{entity.id}}')" class="btn btn-xs btn-info"><i class="fa fa-folder-open"></i> </button>
    </td>
</tr>
    

src/Richpolis/PublicidadBundle/Resources/views/Publicidad/show.html.twig
{% extends 'BackendBundle::layout.html.twig' %}

{% block stylesheets%}
    <!-- Stylesheets -->
  <link rel="stylesheet" href="{{asset('css/bootstrap.css')}}">
  <!-- Font awesome icon -->
  <link rel="stylesheet" href="{{asset('css/font-awesome.css')}}"> 
  <!-- jQuery UI -->
  <link rel="stylesheet" href="{{asset('css/jquery-ui-1.9.2.custom.min.css')}}"> 
  <!-- Calendar -->
  <link rel="stylesheet" href="{{asset('css/fullcalendar.css')}}">
  <!-- prettyPhoto -->
  <link rel="stylesheet" href="{{asset('css/prettyPhoto.css')}}">  
  <!-- Star rating -->
  <link rel="stylesheet" href="{{asset('css/rateit.css')}}">
  <!-- Date picker -->
  <link rel="stylesheet" href="{{asset('css/bootstrap-datetimepicker.min.css')}}">
  <!-- CLEditor -->
  <link rel="stylesheet" href="{{asset('css/jquery.cleditor.css')}}"> 
  <!-- Uniform -->
  <link rel="stylesheet" href="{{asset('css/uniform.default.html')}}"> 
  <!-- Uniform -->
  <link rel="stylesheet" href="{{asset('css/daterangepicker-bs3.css')}}" />
  <!-- Bootstrap toggle -->
  <link rel="stylesheet" href="{{asset('css/bootstrap-switch.css')}}">
    <!-- Bootstrap toggle -->
  <link rel="stylesheet" href="{{asset('js/datatables/css/dataTables.bootstrap.css')}}">
  <!-- Main stylesheet -->
  <link rel="stylesheet" href="{{asset('css/style.css')}}">
  <!-- Widgets stylesheet -->
  <link rel="stylesheet" href="{{asset('css/widgets.css')}}">   
    <!-- Gritter Notifications stylesheet -->
  <link rel="stylesheet" href="{{asset('css/jquery.gritter.css')}}"> 

{% endblock %}

{% block mainbar %}
    <!-- Main bar -->
    <div class="mainbar">

        <!-- Page heading -->
        <div class="page-head">
            <h2 class="pull-left">Publicidad</h2>
            <div class="clearfix"></div>
            <!-- Breadcrumb -->
            <div class="bread-crumb">
                <a href="{{path('backend_homepage')}}"><i class="fa fa-home"></i>Dashboard</a--> 
                    <Divider>
                        <span class="divider">/</span> 
                        <a href="{{path('publicidad')}}" class="bread-current">Publicidad</a>
                        <a href="{{path('publicidad_new')}}" class="btn btn-info pull-right" style="color: white; margin-left: 5px;">Crear publicidad</a>
                        </div>

                        <div class="clearfix"></div>

                        </div>
                        <!-- Page heading ends -->

                        <!-- Matter -->

                        <div class="matter">
                            <div class="container" id="contenidoPagina">
                                <div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="widget">
                                                <div class="widget-head">
                                                    <div class="pull-left">Registro {{entity.id}}</div>
                                                    <div class="clearfix"></div>
                                                </div>

                                                <div class="widget-content">
                                                    <div class="padd">
                                                        <table>
                                                            <tbody>
                                                                <tr>
                                                                    <th>Id</th>
                                                                    <td>{{ entity.id }}</td>
                                                                </tr>
                                                                <tr>
                                                                    <th>Empresa</th>
                                                                    <td>{{ entity.empresa }}</td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Archivo:</td>
                                                                    <td>
                                                                        {% if entity.archivo | length > 0 %}
                                                                            {{ entity.archivoView | raw }}
                                                                        {% else %}    
                                                                            sin archivo
                                                                        {% endif %}
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Link:</td>
                                                                    <td>
                                                                        {% if entity.link | length > 0 %}
                                                                            <a href="{{ entity.webPath }}" target="_blank">{{entity.link}}</a>
                                                                        {% endif %}
                                                                    </td>
                                                                </tr>
																<tr>
                                                                    <th>Tipo publicidad</th>
                                                                    <td>{{ entity.stringTipoPublicidad }}</td>
                                                                </tr>
																<tr>
                                                                    <th>Vigencia</th>
                                                                    <td>{{ entity.vigencia|date('Y-m-d H:i:s') }}</td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Activo?:</td>
                                                                    <td>
                                                                        {% if entity.isActive %}
                                                                            <i class="fa fa-check-circle"></i>
                                                                        {% else %}
                                                                            <i class="fa fa-circle"></i>
                                                                        {% endif %}
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <th>Creado</th>
                                                                    <td>{{ entity.createdAt|date('Y-m-d H:i:s') }}</td>
                                                                </tr>
                                                                <tr>
                                                                    <th>Actualizado</th>
                                                                    <td>{{ entity.updatedAt|date('Y-m-d H:i:s') }}</td>
                                                                </tr>
                                                                
                                                            </tbody>
                                                        </table>    
                                                    </div>
                                                </div>
                                                <div class="widget-foot">
                                                    <button id="botonRegresar" class="btn btn-default" onclick="javascript:regresar('{{path('publicidad')}}')">Regresar</button>
                                                    <button id="botonEditar" class="btn btn-info" onclick="javascript:editarRegistro('{{path('publicidad_edit',{id: entity.id})}}')">Editar</button>
                                                    <div style="float: left; margin-right: 3px;">
                                                        <form id="formEliminar" action="{{ path('publicidad_delete', { 'id': entity.id }) }}" method="post">
                                                           <input type="hidden" name="_method" value="DELETE">
                                                           {{ form_widget(delete_form) }}
                                                        </form>
                                                        <button class="btn btn-danger" onclick="eliminarRegistro();">Eliminar</button>
                                                    </div>        
                                                </div>
                                            </div>  
                                        </div>    
                                    </div>
                                </div>
                            </div>
                        </div>

    <!-- Matter ends -->

    </div>

    <!-- Mainbar ends -->        
    <div class="clearfix"></div>

{% endblock %}

{% block javascripts %}
  {{ parent() }}

<script src="{{asset('js/jquery-ui-1.9.2.custom.min.js')}}"></script> <!-- jQuery UI -->
<script src="{{asset('js/fullcalendar.min.js')}}"></script> <!-- Full Google Calendar - Calendar -->
<script src="{{asset('js/jquery.rateit.min.js')}}"></script> <!-- RateIt - Star rating -->
<script src="{{asset('js/jquery.prettyPhoto.js')}}"></script> <!-- prettyPhoto -->

<!-- jQuery Flot -->
<script src="{{asset('js/excanvas.min.js')}}"></script>
<script src="{{asset('js/jquery.flot.js')}}"></script>
<script src="{{asset('js/jquery.flot.resize.js')}}"></script>
<script src="{{asset('js/jquery.flot.pie.js')}}"></script>
<script src="{{asset('js/jquery.flot.stack.js')}}"></script>

<!-- jQuery Notification - Noty -->
<script src="{{asset('js/jquery.noty.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/themes/default.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/bottom.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/topRight.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/top.js')}}"></script> <!-- jQuery Notify -->
<!-- jQuery Notification ends -->

<script src="{{asset('js/datatables/js/jquery.dataTables.js')}}"></script>

<script src="{{asset('js/sparklines.js')}}"></script> <!-- Sparklines -->
<script src="{{asset('js/jquery.cleditor.min.js')}}"></script> <!-- CLEditor -->
<script src="{{asset('js/bootstrap-datetimepicker.min.js')}}"></script> <!-- Date picker -->
<script src="{{asset('js/jquery.uniform.min.html')}}"></script> <!-- jQuery Uniform -->
<script src="{{asset('js/jquery.slimscroll.min.js')}}"></script> <!-- jQuery SlimScroll -->
<script src="{{asset('js/bootstrap-switch.min.js')}}"></script> <!-- Bootstrap Toggle -->
<script src="{{asset('js/bootbox.min.js')}}"></script> <!-- Filter for support page -->
<script src="{{asset('js/custom.js')}}"></script> <!-- Custom codes -->
<script src="{{asset('js/charts.js')}}"></script> <!-- Charts & Graphs -->


<script>
var regresar = function(url){
    location.href=url;
};

var editarRegistro = function(url){
    location.href=url;
};
    
var eliminarRegistro = function(){
  debugger;
  {% if is_granted('ROLE_ADMIN') %}
    bootbox.confirm("Esta seguro de eliminar el registro?", function(result) {
      if(result){
         $("#formEliminar").submit();
      }
    });
  {% else %}
    noty({text: 'No tienes los permisos suficientes para realizar esta accion',layout:'bottom', type:'warning', timeout:2000 });
  {% endif %}      
};

</script>

    
{% endblock %}

src/Richpolis/PublicidadBundle/Resources/views/Publicidad/ul.html.twig
<ul>
    {% for key, value in tipos %}
        <li>
            <a href="{{ path('publicidad_por_tipo', { 'tipoPublicidad': key }) }}"> 
                <span>{{ value }}</span>
            </a> 
        </li>
    {% endfor %}
</ul>